- hosts: homelab
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot the server (if required)
      reboot:
      when: reboot_required_file.stat.exists

    - name: Wait for the host to come back online
      wait_for_connection:
        delay: 10
      when: reboot_required_file.stat.exists

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker Compose is installed
      apt:
        name: docker-compose
        state: present

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Create Docker network for services
      docker_network:
        name: homelab_network
        driver: bridge
