version: '3.3'

services:
  hyperhdr:
    image: debian:bullseye
    container_name: hyperhdr
    command: >
      bash -c "
      groupadd -f hyperhdr &&
      (id -u hyperhdr &>/dev/null || adduser --uid ${UID:-1000} --gid ${GID:-1000} --no-create-home --disabled-password hyperhdr) &&
      chown ${UID:-1000}:${GID:-1000} /home/hyperhdr &&
      apt-get update &&
      DEBIAN_FRONTEND=noninteractive apt-get upgrade -y &&
      DEBIAN_FRONTEND=noninteractive apt-get install -y wget gpg sudo curl dpkg lsb-release &&
      wget -qO /usr/share/keyrings/hyperhdr.public.apt.gpg.key https://awawa-dev.github.io/hyperhdr.public.apt.gpg.key &&
      chmod go+r /usr/share/keyrings/hyperhdr.public.apt.gpg.key &&
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hyperhdr.public.apt.gpg.key] https://awawa-dev.github.io $(lsb_release -cs) main" > /etc/apt/sources.list.d/hyperhdr.list &&
      apt-get update &&
      DEBIAN_FRONTEND=noninteractive apt-get install -y hyperhdr &&
      apt-get clean &&
      exec sudo -u hyperhdr /usr/bin/hyperhdr -v --service
      "
    ports:
      - "19400:19400"
      - "19444:19444"
      - "19445:19445"
      - "8090:8090"
      - "8092:8092"
    volumes:
      - /volume1/docker/hyperhdr/config:/home/hyperhdr
    restart: unless-stopped
    environment:
      - UID=1000
      - GID=1000
