- name: Ensure Docker and Docker Compose are installed
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker.io
    - docker-compose
  become: true

- name: Copy docker-compose.yml to the target host
  copy:
    src: files/docker-compose.yml
    dest: /home/hyperhdr/docker-compose.yml
  become: true

- name: Create Docker network for HyperHDR
  docker_network:
    name: homelab_network
    driver: bridge
  become: true

- name: Start HyperHDR using Docker Compose
  docker_compose:
    project_src: /home/hyperhdr
    state: present
  become: true
